export const colors = {
  bg: '#0b0f1a',
  bgCard: 'rgba(255,255,255,0.02)',
  bgPanel: 'rgba(255,255,255,0.03)',
  bgInput: 'rgba(255,255,255,0.04)',
  bgHover: 'rgba(255,255,255,0.06)',
  border: 'rgba(255,255,255,0.06)',
  borderLight: 'rgba(255,255,255,0.08)',
  borderInput: 'rgba(255,255,255,0.1)',
  text: '#e2e8f0',
  textSub: '#94a3b8',
  textMuted: '#64748b',
  textDim: '#475569',
  accent: '#60a5fa',
  accentPurple: '#a78bfa',
  white: '#f1f5f9',
};

export const s = {
  root: {
    minHeight: '100dvh',
    background: colors.bg,
    color: colors.text,
    fontFamily: "'Noto Sans JP', -apple-system, sans-serif",
    paddingBottom: 72,
    WebkitFontSmoothing: 'antialiased',
  },
  topBar: {
    background: 'rgba(15,20,35,0.95)',
    backdropFilter: 'blur(12px)',
    WebkitBackdropFilter: 'blur(12px)',
    borderBottom: `1px solid ${colors.border}`,
    padding: '12px 16px',
    paddingTop: 'max(12px, env(safe-area-inset-top))',
    position: 'sticky',
    top: 0,
    zIndex: 20,
  },
  container: {
    maxWidth: 960,
    margin: '0 auto',
    padding: '0 12px',
    width: '100%',
  },
  h1: {
    fontSize: 18,
    fontWeight: 800,
    background: 'linear-gradient(135deg, #60a5fa, #a78bfa)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    marginBottom: 2,
  },
  search: {
    width: '100%',
    padding: '10px 14px',
    borderRadius: 8,
    border: `1px solid ${colors.borderInput}`,
    background: colors.bgInput,
    color: colors.text,
    fontSize: 14,
    fontFamily: 'inherit',
    outline: 'none',
    marginTop: 10,
    WebkitAppearance: 'none',
  },
  catBtn: (active, color) => ({
    padding: '6px 10px',
    borderRadius: 6,
    border: `1.5px solid ${active ? color : colors.borderLight}`,
    background: active ? `${color}20` : 'transparent',
    color: active ? color : colors.textMuted,
    cursor: 'pointer',
    fontSize: 11,
    fontWeight: 600,
    fontFamily: 'inherit',
    transition: 'all 0.15s',
    whiteSpace: 'nowrap',
  }),
  card: (isSelected, isRelated, color) => ({
    padding: '14px 16px',
    borderRadius: 12,
    border: `1.5px solid ${isSelected ? color : isRelated ? `${color}66` : colors.border}`,
    background: isSelected ? `${color}12` : isRelated ? `${color}08` : colors.bgCard,
    cursor: 'pointer',
    transition: 'all 0.2s',
    position: 'relative',
    overflow: 'hidden',
    WebkitTapHighlightColor: 'transparent',
  }),
  badge: (color) => ({
    fontSize: 10,
    fontWeight: 700,
    padding: '2px 8px',
    borderRadius: 4,
    background: `${color}25`,
    color: color,
    letterSpacing: '0.03em',
  }),
  detailPanel: {
    background: colors.bgPanel,
    border: `1px solid ${colors.borderLight}`,
    borderRadius: 14,
    padding: 20,
    marginBottom: 16,
  },
  tabBtn: (active) => ({
    padding: '6px 16px',
    borderRadius: 6,
    border: 'none',
    background: active ? 'rgba(96,165,250,0.15)' : 'transparent',
    color: active ? colors.accent : colors.textMuted,
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 700,
    fontFamily: 'inherit',
    transition: 'all 0.15s',
    WebkitTapHighlightColor: 'transparent',
  }),
  bottomNav: {
    position: 'fixed',
    bottom: 0,
    left: 0,
    right: 0,
    background: 'rgba(15,20,35,0.98)',
    backdropFilter: 'blur(12px)',
    WebkitBackdropFilter: 'blur(12px)',
    borderTop: `1px solid ${colors.border}`,
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingBottom: 'max(8px, env(safe-area-inset-bottom))',
    paddingTop: 8,
    zIndex: 30,
  },
  navItem: (active) => ({
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 2,
    padding: '4px 16px',
    cursor: 'pointer',
    color: active ? colors.accent : colors.textMuted,
    fontSize: 10,
    fontWeight: active ? 700 : 500,
    fontFamily: 'inherit',
    background: 'none',
    border: 'none',
    WebkitTapHighlightColor: 'transparent',
    transition: 'color 0.15s',
  }),
  modal: {
    position: 'fixed',
    inset: 0,
    background: colors.bg,
    zIndex: 50,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'auto',
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    paddingTop: 'max(12px, env(safe-area-inset-top))',
    borderBottom: `1px solid ${colors.border}`,
    background: 'rgba(15,20,35,0.95)',
    backdropFilter: 'blur(12px)',
    position: 'sticky',
    top: 0,
    zIndex: 10,
  },
  modalBody: {
    padding: 16,
    flex: 1,
    overflow: 'auto',
  },
  input: {
    width: '100%',
    padding: '10px 14px',
    borderRadius: 8,
    border: `1px solid ${colors.borderInput}`,
    background: colors.bgInput,
    color: colors.text,
    fontSize: 14,
    fontFamily: 'inherit',
    outline: 'none',
    WebkitAppearance: 'none',
  },
  textarea: {
    width: '100%',
    padding: '10px 14px',
    borderRadius: 8,
    border: `1px solid ${colors.borderInput}`,
    background: colors.bgInput,
    color: colors.text,
    fontSize: 14,
    fontFamily: 'inherit',
    outline: 'none',
    resize: 'vertical',
    minHeight: 100,
    lineHeight: 1.7,
    WebkitAppearance: 'none',
  },
  select: {
    width: '100%',
    padding: '10px 14px',
    borderRadius: 8,
    border: `1px solid ${colors.borderInput}`,
    background: colors.bgInput,
    color: colors.text,
    fontSize: 14,
    fontFamily: 'inherit',
    outline: 'none',
    WebkitAppearance: 'none',
    appearance: 'none',
  },
  btnPrimary: {
    padding: '10px 20px',
    borderRadius: 8,
    border: 'none',
    background: colors.accent,
    color: '#fff',
    fontSize: 14,
    fontWeight: 700,
    fontFamily: 'inherit',
    cursor: 'pointer',
    WebkitTapHighlightColor: 'transparent',
  },
  btnSecondary: {
    padding: '10px 20px',
    borderRadius: 8,
    border: `1px solid ${colors.borderLight}`,
    background: 'transparent',
    color: colors.textSub,
    fontSize: 14,
    fontWeight: 600,
    fontFamily: 'inherit',
    cursor: 'pointer',
    WebkitTapHighlightColor: 'transparent',
  },
  btnDanger: {
    padding: '10px 20px',
    borderRadius: 8,
    border: 'none',
    background: 'rgba(239,68,68,0.15)',
    color: '#ef4444',
    fontSize: 14,
    fontWeight: 700,
    fontFamily: 'inherit',
    cursor: 'pointer',
    WebkitTapHighlightColor: 'transparent',
  },
  btnSmall: {
    padding: '4px 10px',
    borderRadius: 5,
    border: `1px solid ${colors.borderLight}`,
    background: 'transparent',
    color: colors.textSub,
    fontSize: 11,
    fontWeight: 600,
    fontFamily: 'inherit',
    cursor: 'pointer',
    WebkitTapHighlightColor: 'transparent',
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: colors.textMuted,
    marginBottom: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  highlight: {
    background: 'rgba(96,165,250,0.2)',
    borderBottom: '2px solid rgba(96,165,250,0.5)',
    padding: '1px 0',
    borderRadius: 2,
    cursor: 'pointer',
  },
  emptyState: {
    textAlign: 'center',
    padding: '32px 16px',
    color: colors.textDim,
    fontSize: 13,
  },
  label: {
    fontSize: 12,
    fontWeight: 600,
    color: colors.textMuted,
    marginBottom: 6,
    display: 'block',
  },
  formGroup: {
    marginBottom: 16,
  },
};
